#!/bin/bash
alias nv='emacs'
alias ev='emacsclient -t -a=""'
alias mail='mbsync -a && notmuch new && neomutt'
alias rg='ranger'
alias srczb='source ~/.bash_aliases && source ~/.zshrc'
alias dr='~/.emacs.d/bin/doom refresh'
alias cat='bat'
alias gh='cd ~'
alias gr='cd /'
alias lp='ps -aux | grep'
alias kill='sudo kill -9'
alias cmd='marker get'
alias sc='bat ~/.bash_aliases'
# you can add a filename after the following to update only it
alias updot='rcup -v'
